# --- Spring Boot Settings ---
server.port=${PORT:8080}


# --- PostgreSQL (Conversation DB) ---
# spring.datasource.url=jdbc:postgresql://localhost:5432/chatbot
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# --- Redis (for session/memory cache) ---
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.web.resources.static-locations=classpath:/static/

# --- Gemini API ---
gemini.api.key=AIzaSyDILqvWCW1rM_9eE6vx8G4wGZRsJyehlSI
#${GEMINI_API_KEY}
